mode: deployment
replicaCount: 1
fullnameOverride: otel-collector
image:
  repository: otel/opentelemetry-collector-contrib
serviceAccount:
  create: true
  name: otel-collector
  annotations:
    iam.gke.io/gcp-service-account: otel-collector-sa@otel-gke-obervability.iam.gserviceaccount.com
presets:
  kubernetesAttributes:
    enabled: true
resources:
  requests: {cpu: 100m, memory: 256Mi}
  limits: {memory: 512Mi}
ports:
  jaeger-compact: {enabled: false}
  jaeger-thrift: {enabled: false}
  jaeger-grpc: {enabled: false}
  zipkin: {enabled: false}
config:
  receivers:
    otlp:
      protocols:
        grpc: {endpoint: 0.0.0.0:4317}
        http: {endpoint: 0.0.0.0:4318}
  processors:
    memory_limiter: {check_interval: 1s, limit_percentage: 80, spike_limit_percentage: 25}
    resourcedetection: {detectors: [env, gcp], timeout: 2s, override: false}
    batch: {send_batch_size: 200, send_batch_max_size: 200, timeout: 5s}
  exporters:
    debug: {verbosity: basic}
    googlecloud:
      project: otel-gke-obervability
      log: {default_log_name: otel-demo}
    googlemanagedprometheus:
      project: otel-gke-obervability
    prometheusremotewrite:
      endpoint: http://prometheus-server.monitoring.svc.cluster.local/api/v1/write
      tls: {insecure: true}
      resource_to_telemetry_conversion: {enabled: true}
  connectors:
    spanmetrics:
      metrics_flush_interval: 15s
      histogram:
        explicit:
          buckets: [5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s, 2s, 5s]
  service:
    pipelines:
      traces:  {receivers: [otlp], processors: [memory_limiter, resourcedetection, batch], exporters: [googlecloud, spanmetrics, debug]}
      metrics: {receivers: [otlp, spanmetrics], processors: [memory_limiter, resourcedetection, batch], exporters: [googlemanagedprometheus, prometheusremotewrite, debug]}
      logs:    {receivers: [otlp], processors: [memory_limiter, resourcedetection, batch], exporters: [googlecloud, debug]}